ASK_SHOW = {
  name: 'What is your name?',
  greet: 'I don\'t care, loser! You\'re gonna empty your bank.',
  bank: 'Your Bank consists of poor',
  start: 'Press Enter and watch me win!',
  your_cards: 'Your cards: ',
  your_score: 'Your score:',
  my_cards: 'My cards: ** **',
  my_score: 'My score:',
  current_bank: 'Your bank: ',
  bet: 'Current bet:',
  action: 'What do you wanna do?',
  skip: '1) Skip',
  get_card: '2) Get 1 extra card',
  reveal: '3) Reveal cards',
  player_skips: 'You skipped. Now it\'s my turn',
  dealer_skips: 'I skipped. Your turn.',
  player_extra: 'You took 1 extra card:',
  dealer_extra: 'I took 1 extra card.',
  dealer_cards: 'My cards:',
  player_won: 'Okay. You win. But remember, next time I\'ll destroy you!',
  dealer_won: 'Told ya! This is my territory, dude!',
  play_again: 'Do you wanna play again?',
  yep: '1) Sure!',
  nah: '2) Nope.',
  dealer_reveal: 'My cards:',
  draw: 'Draw! Good 4 ya.',
  your_turn: 'Your Turn!',
  bye: 'Bye-bye!'
}.freeze
